### ISSUE TITLE
如何解决eagle内插件面板打不开的问题

### ISSUE THREAD

**Issue by obscurefreeman** [pecasha/eagle-plugin-alpha-video-format-extension#1]
如图，无论在公司还是在家里我都无法打开插件面板，甚至开了加速器都没用。网页端倒是可以打开，但这些插件无法直接下载，点击后转到 eagle 一直在加载。
![image](https://github.com/user-attachments/assets/03a98d58-ff69-403b-8906-2bf49ba17a2d)

**Comment by pecasha** [comment]
这个问题你要跟 Eagle 官方联系反馈
[https://docs-cn.eagle.cool/](https://docs-cn.eagle.cool/) 可以在这个页面右上角的 `联络我们` 中获取 Eagle 官方的技术支持
